//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SS.Mvc.AxosoftApi.Properties
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SS.Mvc.AxosoftApi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Account Locked.
        /// </summary>
        public static string AccountLocked
        {
            get
            {
                return ResourceManager.GetString("AccountLocked", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Account Not Confirmed.
        /// </summary>
        public static string AccountNotConfirmed
        {
            get
            {
                return ResourceManager.GetString("AccountNotConfirmed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SS.Mvc.AxosoftApi.
        /// </summary>
        public static string ApplicationName
        {
            get
            {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Confirm your Email.
        /// </summary>
        public static string ConfirmEmail
        {
            get
            {
                return ResourceManager.GetString("ConfirmEmail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ConfirmPassword
        {
            get
            {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email
        {
            get
            {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        public static string EmailAddress
        {
            get
            {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Email Confirmation Error.
        /// </summary>
        public static string EmailConfirmationError
        {
            get
            {
                return ResourceManager.GetString("EmailConfirmationError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Email Confirmed.
        /// </summary>
        public static string EmailConfirmationSuccess
        {
            get
            {
                return ResourceManager.GetString("EmailConfirmationSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The {0} field is required..
        /// </summary>
        public static string FieldIsRequired
        {
            get
            {
                return ResourceManager.GetString("FieldIsRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The {0} field cannot exceed {1} characters long..
        /// </summary>
        public static string FieldMaxLengthMessage
        {
            get
            {
                return ResourceManager.GetString("FieldMaxLengthMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The {0} field must be between {2} and {1} characters long..
        /// </summary>
        public static string FieldMinMaxLengthMessage
        {
            get
            {
                return ResourceManager.GetString("FieldMinMaxLengthMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to access this page or resource..
        /// </summary>
        public static string FobiddenDescription
        {
            get
            {
                return ResourceManager.GetString("FobiddenDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Forbidden.
        /// </summary>
        public static string Forbidden
        {
            get
            {
                return ResourceManager.GetString("Forbidden", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string ForgotPassword
        {
            get
            {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Forgot Password Confirmation.
        /// </summary>
        public static string ForgotPasswordConfirmation
        {
            get
            {
                return ResourceManager.GetString("ForgotPasswordConfirmation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home
        {
            get
            {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Internal Server Error.
        /// </summary>
        public static string InternalServerError
        {
            get
            {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password..
        /// </summary>
        public static string InvalidCredentials
        {
            get
            {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The user name or password provided is incorrect..
        /// </summary>
        public static string InvalidLoginCredentials
        {
            get
            {
                return ResourceManager.GetString("InvalidLoginCredentials", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The current password is incorrect or the new password is invalid..
        /// </summary>
        public static string InvalidPasswords
        {
            get
            {
                return ResourceManager.GetString("InvalidPasswords", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LogIn
        {
            get
            {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please log in.
        /// </summary>
        public static string LogInMessage
        {
            get
            {
                return ResourceManager.GetString("LogInMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Log in to your account.
        /// </summary>
        public static string LoginTitle
        {
            get
            {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string LogOut
        {
            get
            {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name
        {
            get
            {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string NewPassword
        {
            get
            {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Not Found.
        /// </summary>
        public static string NotFound
        {
            get
            {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The page or resource you have requested does not exist.
        /// </summary>
        public static string NotFoundDescription
        {
            get
            {
                return ResourceManager.GetString("NotFoundDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string OldPassword
        {
            get
            {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password
        {
            get
            {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} characters long..
        /// </summary>
        public static string PasswordLengthMessage
        {
            get
            {
                return ResourceManager.GetString("PasswordLengthMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        public static string PasswordsDoNotMatch
        {
            get
            {
                return ResourceManager.GetString("PasswordsDoNotMatch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register
        {
            get
            {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string RememberMe
        {
            get
            {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string ResetPassword
        {
            get
            {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reset Password Confirmation.
        /// </summary>
        public static string ResetPasswordConfirmation
        {
            get
            {
                return ResourceManager.GetString("ResetPasswordConfirmation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit
        {
            get
            {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unknown Error.
        /// </summary>
        public static string UnknownError
        {
            get
            {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string UserName
        {
            get
            {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to User name already exists. Please enter a different user name..
        /// </summary>
        public static string UsernameAlreadyExists
        {
            get
            {
                return ResourceManager.GetString("UsernameAlreadyExists", resourceCulture);
            }
        }
    }
}
