//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SS.Mvc.AxosoftApi {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SS.Mvc.AxosoftApi.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;&quot;&gt;&lt;div class=&quot;aHl&quot;&gt;&lt;/div&gt;&lt;div id=&quot;:lr&quot; tabindex=&quot;-1&quot;&gt;&lt;/div&gt;&lt;div id=&quot;:lg&quot; class=&quot;ii gt&quot;&gt;&lt;div id=&quot;:lf&quot; class=&quot;a3s aXjCH msg-9135207026715358745&quot;&gt;&lt;div class=&quot;adM&quot;&gt;
        ///
        ///
        ///
        ///
        ///
        ///&lt;/div&gt;&lt;div bgcolor=&quot;#eeeeee&quot;&gt;&lt;div class=&quot;adM&quot;&gt;
        ///
        ///&lt;/div&gt;&lt;table bgcolor=&quot;#eeeeee&quot; border=&quot;0&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; height=&quot;100%&quot; style=&quot;height:100%&quot; width=&quot;100%&quot;&gt;
        ///&lt;tbody&gt;&lt;tr&gt;
        ///&lt;td align=&quot;center&quot; style=&quot;padding:30px 30px 0&quot; valign=&quot;middle&quot;&gt;
        ///&lt;table bgcolor=&quot;#ffffff&quot; border=&quot;0&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; width=&quot;52 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string body {
            get {
                return ResourceManager.GetString("body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;img src=&apos;cid:{0}&apos;&gt;&lt;p&gt;Hi,&lt;/p&gt;&lt;p&gt;Please &lt;b&gt;&lt;a style=&apos;cursor:pointer;&apos;  href=&apos;{1}/menusurvey/{2}&apos;&gt;CLICK HERE&lt;/a&gt;&lt;/b&gt; to go to the Dinner app and fill the Survey to confirm your meals.&lt;/p&gt;&lt;p&gt;Its very important to confirm your meals &lt;b&gt; into 30 hours&lt;/b&gt; otherwise we should not be able to serve your lunch.&lt;/p&gt;&lt;p&gt;If you have any questions or concern, please let the &lt;b&gt; Administrator &lt;/b&gt; know.&lt;/p&gt;&lt;p&gt;Thank you for helping us improve our business and provide a better service!.&lt;/p&gt;&lt;p&gt;Regards,&lt;/p&gt;&lt;p&gt;&lt;b&gt;Dinner Team &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BodyTest {
            get {
                return ResourceManager.GetString("BodyTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jonathan.jpg.
        /// </summary>
        public static string ImageUrl {
            get {
                return ResourceManager.GetString("ImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fotoJonathan.
        /// </summary>
        public static string NameImage {
            get {
                return ResourceManager.GetString("NameImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prueba Correo.
        /// </summary>
        public static string TittleMail {
            get {
                return ResourceManager.GetString("TittleMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
    }
}
